CC = gcc -pthread
CFLAGS = -Wall
EXE = ejercicio_kill

all : $(EXE)

.PHONY : clean
clean :
	rm -f *.o core $(EXE)

$(EXE) : % : %.o
	@echo "#---------------------------"
	@echo "# Generando $@ "
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -o $@ $@.o

ejercicio_kill.o : ejercicio_kill.c
	@echo "#---------------------------"
	@echo "# Generando $@ "
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -c $<


# de ejemplo 
arbol:
	@echo Ejecutando ejercicio_arbol
	@./ejercicio_arbol


